# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:44
from __future__ import unicode_literals

import agv05_webserver.systemx.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0010_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=127, null=True, unique=True)),
                ('is_named', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-is_named', 'name', '-created'),
            },
        ),
        migrations.CreateModel(
            name='MapChangeset',
            fields=[
                ('mapchangeset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True, primary_key=True, serialize=False, to='system.MapChangeset')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemx.Map')),
            ],
            bases=('system.mapchangeset',),
        ),
        migrations.CreateModel(
            name='MapOcg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=127, null=True, unique=True)),
                ('metadata', models.TextField(blank=True, default='')),
                ('png_file', models.ImageField(upload_to=agv05_webserver.systemx.models.get_mapocg_upload_to)),
                ('is_named', models.BooleanField(default=False)),
                ('is_autosaved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemx.Map')),
            ],
            options={
                'ordering': ('-is_named', 'name', '-created'),
                'verbose_name': 'raw map',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('system.variable',),
        ),
        migrations.AddField(
            model_name='mapchangeset',
            name='ocg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systemx.MapOcg'),
        ),
    ]
