# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 11:08
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def create_feature_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    auth = apps.get_app_config('auth')
    systemx = apps.get_app_config('systemx')

    auth.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(auth, verbosity=0)
    create_permissions(auth, verbosity=0)

    systemx.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(systemx, verbosity=0)
    create_permissions(systemx, verbosity=0)

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # Permission objects
    change_mapocg = Permission.objects.get(content_type__app_label='systemx', codename='change_mapocg')
    delete_mapocg = Permission.objects.get(content_type__app_label='systemx', codename='delete_mapocg')
    add_mapchangeset = Permission.objects.get(content_type__app_label='systemx', codename='add_mapchangeset')
    change_mapchangeset = Permission.objects.get(content_type__app_label='systemx', codename='change_mapchangeset')

    group_sv.permissions.add(
        change_mapocg, delete_mapocg,
        add_mapchangeset, change_mapchangeset)

    # Put in a try...except block because the permission is obsolete and might not be found.
    try:
        change_map = Permission.objects.get(content_type__app_label='systemx', codename='change_map')
        delete_map = Permission.objects.get(content_type__app_label='systemx', codename='delete_map')
        group_sv.permissions.add(change_map, delete_map)
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('systemx', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.RunPython(create_feature_group),
    ]
