# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 01:55
from __future__ import unicode_literals

from django.db import migrations, models


# Relocate model to system app. See http://stackoverflow.com/a/26472482

def relocate_contenttypes(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(app_label='systemx', model='map').update(app_label='system')


class Migration(migrations.Migration):

    dependencies = [
        ('systemx', '0002_feature_group'),
    ]

    database_operations = [
        migrations.AlterModelTable('Map', 'system_map')
    ]

    state_operations = [
        migrations.AlterField(
            model_name='mapchangeset',
            name='map_to_be_removed',
            field=models.IntegerField(db_column='map_to_be_removed_id'),
        ),
        migrations.AlterField(
            model_name='mapocg',
            name='map',
            field=models.IntegerField(db_column='map_id'),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapchangeset',
            old_name='map',
            new_name='map_to_be_removed',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        ),
        migrations.RunPython(
            relocate_contenttypes,
            migrations.RunPython.noop,
        ),
    ]
