# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


# Relocate model to system app. See http://stackoverflow.com/a/26472482

def update_mapchangeset(apps, schema_editor):
    MapChangeset = apps.get_model('systemx', 'mapchangeset')
    MapChangeset.objects.update(map=models.expressions.RawSQL(
        'SELECT `systemx_mapchangeset`.`map_to_be_removed_id` FROM `systemx_mapchangeset` ' +
        'WHERE `systemx_mapchangeset`.`mapchangeset_ptr_id` = `system_mapchangeset`.`id`', []))


class Migration(migrations.Migration):

    dependencies = [
        ('systemx', '0003_relocate_map_1'),
        ('system', '0012_map'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='mapchangeset',
            name='map_to_be_removed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Map'),
        ),
        migrations.AlterField(
            model_name='mapocg',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Map'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(
            update_mapchangeset,
            migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='mapchangeset',
            name='map_to_be_removed',
        ),
    ]
