# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemx', '0004_relocate_map_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
