# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemx', '0005_delete_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapocg',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
