# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 10:34
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_feature_group(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    app = apps.get_app_config('app')

    app.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(app, verbosity=0)
    create_permissions(app, verbosity=0)

    user_agv_panel, created = User.objects.get_or_create(username='agv_panel')
    user_agv_panel_pp, created = User.objects.get_or_create(username='agv_panel_pin_protected')

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    show_panel_all_modules = Permission.objects.get(content_type__app_label='app', codename='show_panel_all_modules')
    show_panel_call_buttons = Permission.objects.get(content_type__app_label='app', codename='show_panel_call_buttons')
    show_panel_completed_tasks = Permission.objects.get(content_type__app_label='app', codename='show_panel_completed_tasks')
    show_panel_running_tasks = Permission.objects.get(content_type__app_label='app', codename='show_panel_running_tasks')
    show_panel_side_menu = Permission.objects.get(content_type__app_label='app', codename='show_panel_side_menu')
    wifi_adhoc = Permission.objects.get(content_type__app_label='app', codename='wifi_adhoc')
    wifi_connect = Permission.objects.get(content_type__app_label='app', codename='wifi_connect')

    user_agv_panel.user_permissions.add(show_panel_completed_tasks, show_panel_running_tasks,
        show_panel_call_buttons, show_panel_all_modules, show_panel_side_menu,
        wifi_adhoc, wifi_connect)
    user_agv_panel_pp.user_permissions.add(show_panel_completed_tasks, show_panel_running_tasks,
        show_panel_call_buttons, show_panel_all_modules, show_panel_side_menu,
        wifi_adhoc, wifi_connect)

    group_anon.permissions.add(show_panel_completed_tasks, show_panel_running_tasks)
    group_cb.permissions.add(show_panel_completed_tasks, show_panel_running_tasks,
        show_panel_call_buttons)
    group_user.permissions.add(show_panel_completed_tasks, show_panel_running_tasks,
        show_panel_call_buttons, show_panel_all_modules, show_panel_side_menu,
        wifi_adhoc, wifi_connect)
    group_sv.permissions.add(show_panel_completed_tasks, show_panel_running_tasks,
        show_panel_call_buttons, show_panel_all_modules, show_panel_side_menu,
        wifi_adhoc, wifi_connect)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160915_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={
                'permissions': (
                    ('start_agv05', 'Can start AGV05 controller'),
                    ('stop_agv05', 'Can stop AGV05 controller'),
                    ('soft_reboot', 'Can perform soft reboot'),
                    ('hard_reboot', 'Can perform hard reboot'),
                    ('poweroff', 'Can perform poweroff'),
                    ('show_panel_all_modules', 'Show all modules on panel'),
                    ('show_panel_call_buttons', 'Show call buttons on panel'),
                    ('show_panel_completed_tasks', 'Show completed tasks on panel'),
                    ('show_panel_running_tasks', 'Show running tasks on panel'),
                    ('show_panel_side_menu', 'Show side menu on panel'),
                    ('show_system_icon', 'Show system icon'),
                    ('wifi_adhoc', 'Can on and off adhoc'),
                    ('wifi_connect', 'Can connect and disconnect wifi'))},
        ),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop
        ),
    ]
