# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-28 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={
                'permissions': (
                    ('start_agv05', 'Can start AGV05 controller'),
                    ('stop_agv05', 'Can stop AGV05 controller'),
                    ('soft_reboot', 'Can perform soft reboot'),
                    ('hard_reboot', 'Can perform hard reboot'),
                    ('poweroff', 'Can perform poweroff'),
                    ('start_task_runner', 'Can start Task Runner'),
                    ('stop_task_runner', 'Can stop Task Runner'),
                    ('pause_task_runner', 'Can pause Task Runner'),
                    ('resume_task_runner', 'Can resume Task Runner'),
                    ('start_app', 'Can start app'),
                    ('stop_app', 'Can stop app'),
                    ('show_panel_all_modules', 'Show all modules on panel'),
                    ('show_panel_call_buttons', 'Show call buttons on panel'),
                    ('show_panel_completed_tasks', 'Show completed tasks on panel'),
                    ('show_panel_health_status', 'Show health status on panel'),
                    ('show_panel_live_camera', 'Show live camera on panel'),
                    ('show_panel_live_map', 'Show live map on panel'),
                    ('show_panel_running_tasks', 'Show running tasks on panel'),
                    ('show_panel_side_menu', 'Show side menu on panel'),
                    ('show_system_clock', 'Show system clock'),
                    ('show_system_icon', 'Show link to ConfigPanel'),
                    ('show_popup_safety', 'Show safety message popup'),
                    ('show_popup_user_own', "Show own's user message popup"),
                    ('show_popup_user_public', 'Show public user message popup'),
                    ('show_popup_user_private', 'Show private user message popup'),
                    ('wifi_adhoc', 'Can on and off adhoc'),
                    ('wifi_connect', 'Can connect and disconnect wifi'))},
        ),
    ]
