# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-11 05:28
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_feature_group(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    app = apps.get_app_config('app')

    app.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(app, verbosity=0)
    create_permissions(app, verbosity=0)

    user_agv_panel, created = User.objects.get_or_create(username='agv_panel')
    user_agv_panel_pp, created = User.objects.get_or_create(username='agv_panel_pin_protected')

    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    live_monitor = Permission.objects.get(content_type__app_label='app', codename='show_panel_live_monitor')
    live_manipulation = Permission.objects.get(content_type__app_label='app', codename='show_panel_live_manipulation')

    new_permissions = (live_monitor, live_manipulation)

    user_agv_panel.user_permissions.add(*new_permissions)
    user_agv_panel_pp.user_permissions.add(*new_permissions)

    group_user.permissions.add(*new_permissions)
    group_sv.permissions.add(*new_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={
                'permissions': (
                    ('start_agv05', 'Can start AGV05 controller'),
                    ('stop_agv05', 'Can stop AGV05 controller'),
                    ('soft_reboot', 'Can perform soft reboot'),
                    ('hard_reboot', 'Can perform hard reboot'),
                    ('hot_reload', 'Can perform hot reload'),
                    ('poweroff', 'Can perform poweroff'),
                    ('start_task_runner', 'Can start Task Runner'),
                    ('stop_task_runner', 'Can stop Task Runner'),
                    ('pause_task_runner', 'Can pause Task Runner'),
                    ('resume_task_runner', 'Can resume Task Runner'),
                    ('start_app', 'Can start app'),
                    ('stop_app', 'Can stop app'),
                    ('show_panel_all_modules', 'Show all modules on panel'),
                    ('show_panel_call_buttons', 'Show call buttons on panel'),
                    ('show_panel_completed_tasks', 'Show completed tasks on panel'),
                    ('show_panel_health_status', 'Show health status on panel'),
                    ('show_panel_live_monitor', 'Show live monitor tools on panel'),
                    ('show_panel_live_manipulation', 'Show live manipulation tools on panel'),
                    ('show_panel_live_camera', 'Show live camera on panel'),
                    ('show_panel_live_map', 'Show live map on panel'),
                    ('show_panel_running_tasks', 'Show running tasks on panel'),
                    ('show_panel_side_menu', 'Show side menu on panel'),
                    ('show_system_clock', 'Show system clock'),
                    ('show_system_icon', 'Show link to ConfigPanel'),
                    ('show_popup_safety', 'Show safety message popup'),
                    ('show_popup_user_own', "Show own's user message popup"),
                    ('show_popup_user_public', 'Show public user message popup'),
                    ('show_popup_user_private', 'Show private user message popup'),
                    ('wifi_adhoc', 'Can on and off adhoc'),
                    ('wifi_connect', 'Can connect and disconnect wifi'))},
        ),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop
        ),
    ]
