/*
 * Copyright (c) 2016, DF Automation & Robotics Sdn. Bhd.
 * All rights reserved.
 *
 * Author: Patrick Chin
 */

export default {
  POINTER: 0,
  RULER: 1,
  STATION: 2,
  LANDMARK: 3,
  FORBIDDEN_ZONE: 4,
  NO_ROTATE_ZONE: 5,
  LOC_HINT_ZONE: 6,
  CONNECTOR_STRAIGHT: 11,
  CONNECTOR_BEZIER: 12,
  LIVE_SET_POSE: 20,
  LIVE_GOTO_POSE: 21,
  LIVE_REVERSE_GOTO_POSE: 22,
  LIVE_DYNAMIC_GOTO_POSE: 23,
  LIVE_DYNAMIC_REVERSE_GOTO_POSE: 24,
  LIVE_MANUAL_SET_POSE: 25
};
