# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 03:09
from __future__ import unicode_literals

from django.db import migrations
import subprocess
import uuid


def get_consistent_uuid():
    # use hard disk partition uuid for consistency across database reset.
    try:
        p = subprocess.Popen(['sudo', 'blkid'], stdout=subprocess.PIPE, universal_newlines=True)
        for line in p.stdout.readlines():
            if 'TYPE="ext4"' in line:
                start = line.find('UUID="')
                if start >= 0:
                    start += 6
                    end = line.find('"', start)
                    if end >= 0:
                        return line[start:end]
    except Exception:
        pass

    # generate one if the partition uuid cannot be found.
    return str(uuid.uuid4())


def create_agv_uuid(apps, schema_editor):
    Variable = apps.get_model('system', 'Variable')
    Variable.objects.create(name='agv_uuid', value=get_consistent_uuid())


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_feature_group'),
    ]

    operations = [
        migrations.RunPython(create_agv_uuid),
    ]
