# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_agv_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={
                'permissions': (
                    ('backup_restore', 'Can backup and restore settings'),
                    ('change_help_content', 'Can change help content'),
                    ('view_users', 'Can view users'),
                    ('view_system_panel', 'Can view system panel'))},
        ),
    ]
