# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20160901_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={'ordering': ('-is_active', '-is_top_level', 'name')},
        ),
    ]
