# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0005_auto_20160910_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('task_template_id', models.PositiveIntegerField(null=True)),
                ('task_template', models.CharField(blank=True, default='', max_length=127)),
                ('params', models.TextField(blank=True, default='')),
                ('ccs_task_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[
                    (1, 'Unassigned'),
                    (2, 'Assigned'),
                    (3, 'In_progress'),
                    (4, 'Recovering_error'),
                    (5, 'Cancelling'),
                    (6, 'Completed'),
                    (7, 'Aborted'),
                    (8, 'Cancelled'),
                    (9, 'Incomplete')
                ], db_index=True, default=1)),
                ('sequence', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_after', models.DateTimeField(blank=True, null=True)),
                ('run_start', models.DateTimeField(blank=True, null=True)),
                ('run_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (
                    ('abort_own_task', 'Can abort own task'),
                    ('abort_task', 'Can abort any task'),
                    ('cancel_own_task', 'Can cancel own task'),
                    ('cancel_task', 'Can cancel any task'),
                    ('prioritize_own_task', 'Can prioritize own task'),
                    ('prioritize_task', 'Can prioritize any task')),
            },
        ),
    ]
