# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 10:34
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_feature_group(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    user_agv_panel, created = User.objects.get_or_create(username='agv_panel')
    user_agv_panel_pp, created = User.objects.get_or_create(username='agv_panel_pin_protected')

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    use_tasktemplate = Permission.objects.get(content_type__app_label='system', codename='use_tasktemplate')
    add_task = Permission.objects.get(content_type__app_label='system', codename='add_task')
    abort_own_task = Permission.objects.get(content_type__app_label='system', codename='abort_own_task')
    abort_task = Permission.objects.get(content_type__app_label='system', codename='abort_task')
    cancel_own_task = Permission.objects.get(content_type__app_label='system', codename='cancel_own_task')
    cancel_task = Permission.objects.get(content_type__app_label='system', codename='cancel_task')
    prioritize_own_task = Permission.objects.get(content_type__app_label='system', codename='prioritize_own_task')
    prioritize_task = Permission.objects.get(content_type__app_label='system', codename='prioritize_task')
    change_own_password = Permission.objects.get(content_type__app_label='system', codename='change_own_password')
    view_completed_tasks = Permission.objects.get(content_type__app_label='system', codename='view_completed_tasks')
    view_help_content = Permission.objects.get(content_type__app_label='system', codename='view_help_content')
    try:
        view_map = Permission.objects.get(content_type__app_label='system', codename='view_map')
    except Permission.DoesNotExist:
        view_map = None

    view_panel = Permission.objects.get(content_type__app_label='system', codename='view_panel')

    user_agv_panel.user_permissions.add(add_task,
        abort_own_task, abort_task, cancel_own_task, cancel_task, prioritize_own_task, prioritize_task)
    user_agv_panel_pp.user_permissions.add(add_task,
        abort_own_task, abort_task, cancel_own_task, cancel_task, prioritize_own_task, prioritize_task)

    group_anon.permissions.add(view_panel)
    group_cb.permissions.add(view_panel,
        add_task, abort_own_task, cancel_own_task)
    group_user.permissions.add(view_panel,
        view_completed_tasks, view_help_content, change_own_password,
        add_task, abort_own_task, abort_task, cancel_own_task, cancel_task, prioritize_own_task, prioritize_task)
    group_sv.permissions.add(view_panel,
        view_completed_tasks, view_help_content, change_own_password,
        add_task, abort_own_task, abort_task, cancel_own_task, cancel_task, prioritize_own_task, prioritize_task,
        use_tasktemplate)

    if view_map:
        group_anon.permissions.add(view_map)
        group_cb.permissions.add(view_map)
        group_user.permissions.add(view_map)
        group_sv.permissions.add(view_map)

    # Old permission objects
    # group_cb.permissions.add()


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={
                'ordering': ('-is_active', '-is_top_level', 'name'),
                'permissions': (
                    ('use_tasktemplate', 'Use any task template'),
                )},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={
                'permissions': (
                    ('backup_restore', 'Can backup and restore settings'),
                    ('change_help_content', 'Can change help content'),
                    ('change_own_password', 'Can change own password'),
                    ('view_completed_tasks', 'Can view completed tasks'),
                    ('view_help_content', 'Can view help content'),
                    ('view_map', 'Can view map'),
                    ('view_panel', 'Can view agv panel'),
                    ('view_system_panel', 'Can view system panel'),
                    ('view_users', 'Can view users'))},
        ),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop
        ),
    ]
