# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0007_permissions'),
        ('anon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
