# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 04:20
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_feature_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    view_log_files = Permission.objects.get(content_type__app_label='system', codename='view_log_files')

    group_sv.permissions.add(view_log_files)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_tasktemplate_allowed_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={
                'permissions': (
                    ('backup_restore', 'Can backup and restore settings'),
                    ('change_help_content', 'Can change help content'),
                    ('change_own_password', 'Can change own password'),
                    ('view_completed_tasks', 'Can view completed tasks'),
                    ('view_help_content', 'Can view help content'),
                    ('view_log_files', 'Can view log files'),
                    ('view_map', 'Can view map'),
                    ('view_panel', 'Can view agv panel'),
                    ('view_system_panel', 'Can view system panel'),
                    ('view_users', 'Can view users'))},
        ),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop
        ),
    ]
