# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:01
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_permission_name(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    # Change permission display name
    Permission.objects.filter(content_type__app_label='system', codename='view_panel').update(name='Can view UserPanel')
    Permission.objects.filter(content_type__app_label='system', codename='view_system_panel').update(name='Can view ConfigPanel')


def update_feature_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # Old permission objects
    change_permission = Permission.objects.get(content_type__app_label='auth', codename='change_permission')
    view_system_panel = Permission.objects.get(content_type__app_label='system', codename='view_system_panel')

    group_user.permissions.remove(view_system_panel)
    group_sv.permissions.remove(change_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={
                'permissions': (
                    ('backup_restore', 'Can backup and restore settings'),
                    ('change_help_content', 'Can change help content'),
                    ('change_own_password', 'Can change own password'),
                    ('view_completed_tasks', 'Can view completed tasks'),
                    ('view_help_content', 'Can view help content'),
                    ('view_log_files', 'Can view log files'),
                    ('view_map', 'Can view map'),
                    ('view_panel', 'Can view UserPanel'),
                    ('view_system_panel', 'Can view ConfigPanel'),
                    ('view_users', 'Can view users'))},
        ),
        migrations.RunPython(
            update_permission_name,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop,
        ),
    ]
