# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ccs_task_id',
            new_name='fms_task_id',
        ),
    ]
