# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 01:55
from __future__ import unicode_literals

from django.conf import settings as django_settings
from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations, models
import django.db.models.deletion


# Relocate model from systemx app. See http://stackoverflow.com/a/26472482

def update_feature_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    add_map = Permission.objects.get(content_type__app_label='system', codename='add_map')
    change_map = Permission.objects.get(content_type__app_label='system', codename='change_map')
    delete_map = Permission.objects.get(content_type__app_label='system', codename='delete_map')

    group_sv.permissions.add(add_map, change_map, delete_map)


def create_placeholder_map(apps, schema_editor):
    global placeholder_map_id
    Map = apps.get_model('system', 'map')
    placeholder_map_id = Map.objects.create(name='Migration placeholder', is_named=True).id

    Variable = apps.get_model('system', 'variable')
    Variable.objects.get_or_create(name='active_map', defaults={'value': placeholder_map_id})


def get_placeholder_map_id():
    return placeholder_map_id


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20170327_1720'),
    ]
    if django_settings.TRACKLESS:
        dependencies += [
            ('systemx', '0003_relocate_map_1'),
        ]

    create_model_map = migrations.CreateModel(
        name='Map',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(blank=True, default=None, max_length=127, null=True, unique=True)),
            ('is_named', models.BooleanField(default=False)),
            ('created', models.DateTimeField(auto_now_add=True)),
        ],
        options={
            'ordering': ('-is_named', 'name', '-created'),
        },
    )

    operations = [
        create_model_map if not django_settings.TRACKLESS else
        migrations.SeparateDatabaseAndState(state_operations=[
            create_model_map,
        ]),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop
        ),
        migrations.RunPython(
            create_placeholder_map,
            migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name='mapchangeset',
            name='map',
            field=models.ForeignKey(default=get_placeholder_map_id, on_delete=django.db.models.deletion.CASCADE, to='system.Map'),
            preserve_default=False,
        ),
    ]
