# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='category',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=127, null=True),
        ),
    ]
