# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 08:53
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_feature_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    change_agv = Permission.objects.get(content_type__app_label='system', codename='change_agv')

    group_sv.permissions.add(change_agv)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20170714_0306'),
    ]

    operations = [
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop,
        ),
    ]
