# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 21:54
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_feature_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    auth = apps.get_app_config('auth')

    auth.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(auth, verbosity=0)
    create_permissions(auth, verbosity=0)

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    add_group = Permission.objects.get(content_type__app_label='auth', codename='add_group')
    change_group = Permission.objects.get(content_type__app_label='auth', codename='change_group')
    delete_group = Permission.objects.get(content_type__app_label='auth', codename='delete_group')

    group_sv.permissions.add(add_group, change_group, delete_group)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20170720_1444'),
    ]

    operations = [
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop,
        ),
    ]
