# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Unassigned'),
                    (2, 'Assigned'),
                    (3, 'In Progress'),
                    (4, 'Recovering Error'),
                    (5, 'Cancelling'),
                    (6, 'Completed'),
                    (7, 'Aborted'),
                    (8, 'Cancelled'),
                    (9, 'Incomplete')
                ], db_index=True, default=1),
        ),
    ]
