# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:11
from __future__ import unicode_literals

from django.db import IntegrityError, migrations, models
import six


def import_from_mongodb(apps, schema_editor):
    TaskStatistic = apps.get_model('system', 'TaskStatistic')
    try:
        from django.conf import settings as django_settings
        from django.utils import timezone
        from mongokit import Connection
        import json

        connection = Connection(tz_aware=True)
        connection.register(_get_documents())

        db_name = 'agv05' if not django_settings.TRACKLESS else 'agv05x'
        db = getattr(connection, db_name)

        for ts in db.TaskStatistic.find():
            try:
                TaskStatistic.objects.create(
                    date=timezone.localtime(ts['date']).date(),
                    by_status=json.dumps(ts['by_status']),
                    by_tt=json.dumps(ts['by_tt']))
            except IntegrityError:
                pass
    except Exception:
        pass


def _get_documents():
    from mongokit import Document, DocumentMigration
    import datetime

    class TaskStatistic(Document):
        __collection__ = 'taskstatistic'
        structure = {
            'date': datetime.datetime,
            'by_status': {
                'Completed': {'count': int, 'duration': int},
                'Aborted': {'count': int, 'duration': int},
                'Cancelled': {'count': int, 'duration': int},
            },
            'by_tt': {
                'Completed': [{'task_template': six.text_type, 'count': int, 'duration': int}],
                'Aborted': [{'task_template': six.text_type, 'count': int, 'duration': int}],
                'Cancelled': [{'task_template': six.text_type, 'count': int, 'duration': int}],
            },
        }
        indexes = [
            {'fields': 'date', 'unique': True, 'expireAfterSeconds': 3600 * 24 * 366 * 2},
        ]
        default_values = {
            'by_status.Completed.count': 0,
            'by_status.Completed.duration': 0,
            'by_status.Aborted.count': 0,
            'by_status.Aborted.duration': 0,
            'by_status.Cancelled.count': 0,
            'by_status.Cancelled.duration': 0,
        }

    class TaskStatisticMigration(DocumentMigration):

        def migration_0001_add_duration_field1(self):
            self.target = {
                'by_status.Completed': {'$exists': True},
                'by_status.Completed.count': {'$exists': False},
            }
            self.update = {'$set': {'by_status.Completed': {'count': self.doc['by_status']['Completed'], 'duration': 0}}}

        def migration_0001_add_duration_field2(self):
            self.target = {
                'by_status.Aborted': {'$exists': True},
                'by_status.Aborted.count': {'$exists': False},
            }
            self.update = {'$set': {'by_status.Aborted': {'count': self.doc['by_status']['Aborted'], 'duration': 0}}}

        def migration_0001_add_duration_field3(self):
            self.target = {
                'by_status.Cancelled': {'$exists': True},
                'by_status.Cancelled.count': {'$exists': False},
            }
            self.update = {'$set': {'by_status.Cancelled': {'count': self.doc['by_status']['Cancelled'], 'duration': 0}}}

    TaskStatistic.migration_handler = TaskStatisticMigration
    return [TaskStatistic]


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20170918_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatistic',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('by_status', models.TextField()),
                ('by_tt', models.TextField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.RunPython(
            import_from_mongodb,
            migrations.RunPython.noop,
        ),
    ]
