# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_taskstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[
                (1, 'Unassigned'),
                (2, 'Assigned'),
                (3, 'In Progress'),
                (4, 'Aborting'),
                (5, 'Cancelling'),
                (6, 'Completed'),
                (7, 'Aborted'),
                (8, 'Cancelled'),
                (9, 'Incomplete')
            ], db_index=True, default=1),
        ),
    ]
