# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 04:33
from __future__ import unicode_literals

from django.db import migrations, models


def update_task(apps, schema_editor):
    Task = apps.get_model('system', 'Task')
    Task.objects.filter(status__lt=6).delete()
    Task.objects.filter(params='').update(params='{}')


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='params',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[
                (1, 'Suspended'),
                (2, 'Pending'),
                (3, 'Cancelling'),
                (4, 'In Progress'),
                (5, 'Aborting'),
                (6, 'Completed'),
                (7, 'Aborted'),
                (8, 'Cancelled'),
                (9, 'Incomplete')
            ], db_index=True, default=2),
        ),
        migrations.RunPython(
            update_task,
            migrations.RunPython.noop,
        ),
    ]
