# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 09:38
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_feature_group(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    user_agv_panel, created = User.objects.get_or_create(username='agv_panel')
    user_agv_panel_pp, created = User.objects.get_or_create(username='agv_panel_pin_protected')

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    suspend_own_task = Permission.objects.get(content_type__app_label='system', codename='suspend_own_task')
    suspend_task = Permission.objects.get(content_type__app_label='system', codename='suspend_task')
    resume_own_task = Permission.objects.get(content_type__app_label='system', codename='resume_own_task')
    resume_task = Permission.objects.get(content_type__app_label='system', codename='resume_task')

    user_agv_panel.user_permissions.add(suspend_own_task, suspend_task, resume_own_task, resume_task)
    user_agv_panel_pp.user_permissions.add(suspend_own_task, suspend_task, resume_own_task, resume_task)

    group_user.permissions.add(suspend_own_task, suspend_task, resume_own_task, resume_task)
    group_sv.permissions.add(suspend_own_task, suspend_task, resume_own_task, resume_task)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={
                'permissions': (
                    ('abort_own_task', 'Can abort own task'),
                    ('abort_task', 'Can abort any task'),
                    ('cancel_own_task', 'Can cancel own task'),
                    ('cancel_task', 'Can cancel any task'),
                    ('prioritize_own_task', 'Can prioritize own task'),
                    ('prioritize_task', 'Can prioritize any task'),
                    ('suspend_own_task', 'Can suspend own task'),
                    ('suspend_task', 'Can suspend any task'),
                    ('resume_own_task', 'Can resume own task'),
                    ('resume_task', 'Can resume any task'))},
        ),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop,
        ),
    ]
