# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-05 02:04
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations, models


def update_feature_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    add_webhook = Permission.objects.get(content_type__app_label='system', codename='add_webhook')
    change_webhook = Permission.objects.get(content_type__app_label='system', codename='change_webhook')
    delete_webhook = Permission.objects.get(content_type__app_label='system', codename='delete_webhook')

    group_sv.permissions.add(add_webhook, change_webhook, delete_webhook)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('verify_ssl', models.BooleanField(default=True, verbose_name='enable ssl verification')),
                ('secret_token', models.CharField(blank=True, default='', max_length=64)),
                ('events', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('url',),
            },
        ),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop,
        ),
    ]
