# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 08:45
from __future__ import unicode_literals

from django.db import IntegrityError, migrations
import ujson as json


def create_map_param(apps, schema_editor):
    Variable = apps.get_model('system', 'Variable')
    try:
        Variable.objects.create(name='map_param', value=json.dumps([
            {
                'name': 'Medium Fast',
                'type': 'double',
                'default': 0.6,
            },
            {
                'name': 'Medium',
                'type': 'double',
                'default': 0.5,
            },
            {
                'name': 'Slow',
                'type': 'double',
                'default': 0.4,
            },
        ]))
    except IntegrityError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_webhook'),
    ]

    operations = [
        migrations.RunPython(
            create_map_param,
            migrations.RunPython.noop,
        ),
    ]
