# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-27 09:39
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations, models


def update_feature_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    view_agv_activities = Permission.objects.get(content_type__app_label='system', codename='view_agv_activities')
    change_agv_activities_config = Permission.objects.get(content_type__app_label='system', codename='change_agv_activities_config')
    add_agvactivity = Permission.objects.get(content_type__app_label='system', codename='add_agvactivity')
    change_agvactivity = Permission.objects.get(content_type__app_label='system', codename='change_agvactivity')
    delete_agvactivity = Permission.objects.get(content_type__app_label='system', codename='delete_agvactivity')

    group_user.permissions.add(view_agv_activities)
    group_sv.permissions.add(view_agv_activities, change_agv_activities_config,
        add_agvactivity, change_agvactivity, delete_agvactivity)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_map_param'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgvActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(unique=True)),
                ('activity', models.PositiveSmallIntegerField(choices=[
                    (0, 'Idle'),
                    (1, 'Paused'),
                    (2, 'Working'),
                    (3, 'Charging'),
                    (10, 'Running App'),
                    (80, 'Not Ready'),
                    (81, 'Powered Off'),
                    (82, 'Unplanned Maintenance'),
                    (83, 'Planned Maintenance'),
                    (84, 'System Failure'),
                    (85, 'Hardware Failure'),
                    (100, 'Bumper Blocked'),
                    (101, 'External Safety Trigger'),
                    (102, 'Emergency Button Pressed'),
                    (103, 'Charger Connected'),
                    (104, 'Laser Malfunction'),
                    (105, 'Line Sensor Com Error'),
                    (106, 'Drive Overlimit Error'),
                    (107, 'Motor Fault'),
                    (108, 'Wheel Slippage'),
                    (161, 'Navigation Failed'),
                    (162, 'Out Of Line'),
                    (163, 'Obstacle Blocked'),
                    (199, 'Safety Triggered'),
                    (200, 'Waiting Traffic'),
                    (201, 'Waiting User'),
                    (300, 'Fms Disconnected'),
                    (301, 'Fms Incompatible'),
                    (302, 'Fms Syncing'),
                    (303, 'Fms Sync Pending')])),
            ],
            options={
                'verbose_name_plural': 'agv activities',
            },
        ),
        migrations.CreateModel(
            name='AgvStatistic',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('by_activity', models.TextField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={
                'permissions': (
                    ('backup_restore', 'Can backup and restore settings'),
                    ('change_agv', 'Can change agv'),
                    ('change_agv_activities_config', 'Can change agv activities configuration'),
                    ('change_datetime', 'Can change date and time settings'),
                    ('change_license', 'Can change license key'),
                    ('change_network', 'Can change network configuration'),
                    ('change_own_password', 'Can change own password'),
                    ('update_software', 'Can update software'),
                    ('view_agv_activities', 'Can view agv activities'),
                    ('view_completed_tasks', 'Can view completed tasks'),
                    ('view_help_content', 'Can view help content'),
                    ('view_log_files', 'Can view log files'),
                    ('view_map', 'Can view map'),
                    ('view_panel', 'Can view UserPanel'),
                    ('view_system_panel', 'Can view ConfigPanel'),
                    ('view_users', 'Can view users'))},
        ),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop,
        ),
    ]
