# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-05 01:02
from __future__ import unicode_literals

from django.db import migrations


def update_mileage(apps, schema_editor):
    Variable = apps.get_model('system', 'Variable')

    mileage = 0
    try:
        mileage = max(mileage, float(Variable.objects.get(
            name='/agv05_motor/motor_mileage').value))
    except Exception:
        pass

    try:
        mileage = max(mileage, float(Variable.objects.get(
            name='/agv_motor/motor_mileage').value))
    except Exception:
        pass

    Variable.objects.update_or_create(name='/agv05_motor/mileage', defaults={
        'value': str(mileage),
    })


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_agvactivity_agvstatistic'),
    ]

    operations = [
        migrations.RunPython(
            update_mileage,
            migrations.RunPython.noop,
        ),
    ]
