# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0029_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agvactivity',
            name='activity',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Idle'),
                    (1, 'Paused'),
                    (2, 'Working'),
                    (3, 'Charging'),
                    (10, 'Running App'),
                    (80, 'Not Ready'),
                    (81, 'Powered Off'),
                    (82, 'Unplanned Maintenance'),
                    (83, 'Planned Maintenance'),
                    (84, 'System Failure'),
                    (85, 'Hardware Failure'),
                    (100, 'Bumper Blocked'),
                    (101, 'External Safety Trigger'),
                    (102, 'Emergency Button Pressed'),
                    (103, 'Charger Connected'),
                    (104, 'Laser Malfunction'),
                    (105, 'Line Sensor Com Error'),
                    (106, 'Drive Overlimit Error'),
                    (107, 'Motor Fault'),
                    (108, 'Wheel Slippage'),
                    (161, 'Navigation Failed'),
                    (162, 'Out Of Line'),
                    (163, 'Obstacle Blocked'),
                    (164, 'Path Blocked'),
                    (199, 'Safety Triggered'),
                    (200, 'Waiting Traffic'),
                    (201, 'Waiting User'),
                    (300, 'Fms Disconnected'),
                    (301, 'Fms Incompatible'),
                    (302, 'Fms Syncing'),
                    (303, 'Fms Sync Pending')]),
        ),
    ]
