# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-27 10:57
from __future__ import unicode_literals

from django.conf import settings as django_settings
from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_feature_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    view_map_quality = Permission.objects.get(content_type__app_label='system', codename='view_map_quality')

    if django_settings.TRACKLESS:
        group_sv.permissions.add(view_map_quality)

    # Remove old permission objects
    Permission.objects.filter(content_type__app_label='system', codename='view_map').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0030_auto_20210412_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={
                'permissions': (
                    ('backup_restore', 'Can backup and restore settings'),
                    ('change_agv', 'Can change agv'),
                    ('change_agv_activities_config', 'Can change agv activities configuration'),
                    ('change_datetime', 'Can change date and time settings'),
                    ('change_license', 'Can change license key'),
                    ('change_network', 'Can change network configuration'),
                    ('change_own_password', 'Can change own password'),
                    ('update_software', 'Can update software'),
                    ('view_agv_activities', 'Can view agv activities'),
                    ('view_completed_tasks', 'Can view completed tasks'),
                    ('view_help_content', 'Can view help content'),
                    ('view_log_files', 'Can view log files'),
                    ('view_map_quality', 'Can view map quality'),
                    ('view_panel', 'Can view UserPanel'),
                    ('view_system_panel', 'Can view ConfigPanel'),
                    ('view_users', 'Can view users'))},
        ),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop,
        ),
    ]
