# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-31 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('system', '0032_auto_20221202_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='allowed_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
