# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-22 06:09
from __future__ import unicode_literals

from django.conf import settings as django_settings
from django.db import IntegrityError, migrations
import distutils.util


def relocate_parameter_and_variable(apps, schema_editor):
    if not django_settings.TRACKLESS or getattr(django_settings, 'TESTING', False):
        return

    Parameter = apps.get_model('system', 'Parameter')
    Variable = apps.get_model('system', 'Variable')

    # Move paramater and variable from agv05x database to agv05 database.

    # If current mode is trackless, allow overwrite existing entries on agv05 database.
    # Otherwise, don't overwrite and write only those entries non-existent on agv05 database.
    no_overwrite = not _is_trackless_mode_configured()

    qs = Parameter.objects.all()
    for p in qs:
        try:
            p.save(using='alt', force_insert=no_overwrite)
        except IntegrityError:
            pass
    qs.delete()

    qs = Variable.objects.filter(name__startswith='/').exclude(name__startswith='/agv05_executor/')
    for v in qs:
        try:
            v.save(using='alt', force_insert=no_overwrite)
        except IntegrityError:
            pass
    qs.delete()


def _is_trackless_mode_configured():
    try:
        with open('/etc/default/navwiz-core') as f:
            lines = f.readlines()

        key = 'TRACKLESS='
        for line in reversed(lines):
            if line.startswith(key):
                return distutils.util.strtobool(line[len(key):].strip())
    except Exception:
        pass
    return False


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_add_allowed_groups'),
    ]

    operations = [
        migrations.RunPython(relocate_parameter_and_variable),
    ]
