# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-30 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0035_auto_20230516_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={
                'ordering': ('key',),
                'permissions': (
                    ('change_protected_parameter', 'Can change protected parameter',),
                ),
            },
        ),
    ]
