# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-08 06:16
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_feature_group(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    user_agv_panel, created = User.objects.get_or_create(username='agv_panel')
    user_agv_panel_pp, created = User.objects.get_or_create(username='agv_panel_pin_protected')

    group_anon, created = Group.objects.get_or_create(name='Guest')
    group_cb, created = Group.objects.get_or_create(name='Call Button')
    group_user, created = Group.objects.get_or_create(name='User')
    group_sv, created = Group.objects.get_or_create(name='Supervisor')

    # New permission objects
    abort_transaction = Permission.objects.get(content_type__app_label='system', codename='abort_transaction')
    cancel_transaction = Permission.objects.get(content_type__app_label='system', codename='cancel_transaction')
    resume_transaction = Permission.objects.get(content_type__app_label='system', codename='resume_transaction')

    new_permissions = (abort_transaction, cancel_transaction, resume_transaction)

    user_agv_panel.user_permissions.add(*new_permissions)
    user_agv_panel_pp.user_permissions.add(*new_permissions)

    group_sv.permissions.add(*new_permissions)
    group_user.permissions.add(*new_permissions)
    group_cb.permissions.add(*new_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0036_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={
                'permissions': (
                    ('backup_restore', 'Can backup and restore settings'),
                    ('change_agv', 'Can change agv'),
                    ('change_agv_activities_config', 'Can change agv activities configuration'),
                    ('change_datetime', 'Can change date and time settings'),
                    ('change_license', 'Can change license key'),
                    ('change_network', 'Can change network configuration'),
                    ('change_own_password', 'Can change own password'),
                    ('update_software', 'Can update software'),
                    ('abort_transaction', 'Can abort any transaction'),
                    ('cancel_transaction', 'Can cancel any transaction'),
                    ('resume_transaction', 'Can resume any transaction'),
                    ('view_agv_activities', 'Can view agv activities'),
                    ('view_completed_tasks', 'Can view completed tasks'),
                    ('view_help_content', 'Can view help content'),
                    ('view_log_files', 'Can view log files'),
                    ('view_map_quality', 'Can view map quality'),
                    ('view_panel', 'Can view UserPanel'),
                    ('view_system_panel', 'Can view ConfigPanel'),
                    ('view_users', 'Can view users'))},
        ),
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop,
        ),
    ]
