# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-15 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0037_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotations', models.TextField(blank=True, default='')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.Map')),
            ],
            options={
                'verbose_name': 'map annotation',
            },
        ),
    ]
