# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-08 06:16
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def update_feature_group(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Permission = apps.get_model('auth', 'Permission')
    system = apps.get_app_config('system')

    system.models_module = True  # a trick to get the next two function executed.
    create_contenttypes(system, verbosity=0)
    create_permissions(system, verbosity=0)

    user_agv_panel, created = User.objects.get_or_create(username='agv_panel')
    user_agv_panel_pp, created = User.objects.get_or_create(username='agv_panel_pin_protected')

    view_panel = Permission.objects.get(content_type__app_label='system', codename='view_panel')

    user_agv_panel.user_permissions.add(view_panel)
    user_agv_panel_pp.user_permissions.add(view_panel)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0038_mapannotation'),
    ]

    operations = [
        migrations.RunPython(
            update_feature_group,
            migrations.RunPython.noop,
        ),
    ]
