# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-17 14:02
from __future__ import unicode_literals

from django.conf import settings as django_settings
from django.db import IntegrityError, migrations
import distutils.util


def relocate_variable(apps, schema_editor):
    # Remove old license
    Variable = apps.get_model('system', 'Variable')
    Variable.objects.filter(name__startswith='license_').delete()
    Variable.objects.filter(name='agv_uuid').delete()

    if not django_settings.TRACKLESS or getattr(django_settings, 'TESTING', False):
        return

    # Move protected variables from agv05x database to agv05 database.

    # If current mode is trackless, allow overwrite existing entries on agv05 database.
    # Otherwise, don't overwrite and write only those entries non-existent on agv05 database.
    no_overwrite = not _is_trackless_mode_configured()

    protected = [
        'agv_model',
        'serial_number',
        'manufacture_date',
        'next_pm_due',
        'next_pm_mileage',
    ]
    qs = Variable.objects.filter(name__in=protected)
    for v in qs:
        try:
            v.save(using='alt', force_insert=no_overwrite)
        except IntegrityError:
            pass
    qs.delete()


def _is_trackless_mode_configured():
    try:
        with open('/etc/default/navwiz-core') as f:
            lines = f.readlines()

        key = 'TRACKLESS='
        for line in reversed(lines):
            if line.startswith(key):
                return distutils.util.strtobool(line[len(key):].strip())
    except Exception:
        pass
    return False


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0039_permissions'),
    ]

    operations = ([
        migrations.CreateModel(
            name='VariableRos',
            fields=[
            ],
            options={
                'verbose_name': 'variable (ROS)',
                'proxy': True,
                'verbose_name_plural': 'variables (ROS)',
                'indexes': [],
            },
            bases=('system.variable',),
        ),
    ] if django_settings.TRACKLESS else []) + [
        migrations.RunPython(relocate_variable),
    ]
