"""
Django settings for agv05_webserver project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from __future__ import unicode_literals

import distutils.util
import os
import pytz
import rospkg
import urllib3

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+46x0_))^7rj!=hhfgg6c_qqi2m@gu%n6ff84vq*0p^d#wgqb='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

INTERNAL_IPS = ['127.0.0.1', 'localhost']

ALLOWED_HOSTS = ['*']

ADMINS = (
    ('Patrick Chin', 'patrick@dfautomation.com'),
)

MANAGERS = ADMINS


# Tracked or Trackless

TRACKLESS = False
DYNAMIC_PATH_PLANNING = False
try:
    TRACKLESS = distutils.util.strtobool(os.environ['TRACKLESS'])
    DYNAMIC_PATH_PLANNING = distutils.util.strtobool(os.environ['DYNAMIC_PATH_PLANNING'])
except Exception:
    pass

# Omni

OMNI_DRIVE = False
try:
    OMNI_DRIVE = distutils.util.strtobool(os.environ['OMNI_DRIVE'])
except Exception:
    pass

# No auto poweroff

NO_AUTO_POWER_OFF = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third-party
    'bootstrap3',
    'crispy_forms',
    'django_cleanup',
    'django_extensions',
    'django_filters',
    'djcelery',
    'rest_framework',
    'rest_framework.authtoken',
    # our own
    'agv05_webserver.anon',
    'agv05_webserver.hashicon',
]

if TRACKLESS:
    INSTALLED_APPS.append('agv05_webserver.appx.apps.AppXConfig')
    INSTALLED_APPS.append('agv05_webserver.systemx.apps.SystemxConfig')

INSTALLED_APPS.append('agv05_webserver.app.apps.AppConfig')
INSTALLED_APPS.append('agv05_webserver.system.apps.SystemConfig')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agv05_webserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agv05_webserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'agv05' if not TRACKLESS else 'agv05x',
        'USER': 'agv05',
        'PASSWORD': 'agv05',
        'HOST': '',
        'PORT': '',
    },
    'alt': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'agv05' if TRACKLESS else 'agv05x',
        'USER': 'agv05',
        'PASSWORD': 'agv05',
        'HOST': '',
        'PORT': '',
    },
}


# Cache
# https://docs.djangoproject.com/en/1.10/ref/settings/#caches

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
        'KEY_PREFIX': 'agv05' if not TRACKLESS else 'agv05x',
        'TIMEOUT': None,
        'VERSION': 1,
    },
    'redis': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'KEY_PREFIX': 'agv05' if not TRACKLESS else 'agv05x',
        'TIMEOUT': None,
        'VERSION': 1,
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Authentication

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'agv05_webserver.anon.backends.AnonymousUserBackend',
)

LOGIN_REDIRECT_URL = 'app:index'

LOGIN_URL = 'system:login'


# Cookies

CSRF_COOKIE_NAME = 'agv05_csrftoken' if not TRACKLESS else 'agv05x_csrftoken'
LANGUAGE_COOKIE_NAME = 'agv05_django_language' if not TRACKLESS else 'agv05x_django_language'
SESSION_COOKIE_NAME = 'agv05_sessionid' if not TRACKLESS else 'agv05x_sessionid'
SESSION_COOKIE_AGE = 30 * 365 * 24 * 3600  # 30 years


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-GB'

TIME_ZONE = 'Asia/Kuala_Lumpur'
try:
    with open('/etc/timezone', 'r') as f:
        for line in f:
            tz = line.split('#')[0].strip()
            try:
                pytz.timezone(tz)
            except Exception:
                continue
            TIME_ZONE = tz
            break
except Exception:
    pass

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Media files (user-uploaded files)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

FILE_UPLOAD_PERMISSIONS = 0o664


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    ('system', os.path.join(rospkg.RosPack().get_path('agv05_webserver'), 'assets')),
]

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'


# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'agv05_webserver': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'kombu': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'tornado': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Django Crispy Forms
CRISPY_FAIL_SILENTLY = not DEBUG
CRISPY_TEMPLATE_PACK = 'bootstrap3'


# Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'agv05_webserver.app.authentication.AgvPanelSessionAuthentication',
    ],
    # Use Django's standard 'django.contrib.auth' permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'agv05_webserver.app.pagination.LimitOffsetPagination',
    'DEFAULT_METADATA_CLASS': 'agv05_webserver.app.metadata.SimpleMetadata',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}


# Django Sendfile
SENDFILE_BACKEND = 'sendfile.backends.simple'
SENDFILE_ROOT = MEDIA_ROOT
SENDFILE_URL = MEDIA_URL


# ROS
AGV05_AUDIO_PLAYER = '/agv05_audio_player'
AGV05_EXECUTOR = '/agv05_executor'
WIFI_MANAGER = '/wifi_manager'


# SockJS Server
SOCKJS_CONNECTIONS = {
    # TODO: should we split sockserver?
    '/app': 'agv05_webserver.app.sockserver.Connection',
    '/system': 'agv05_webserver.system.sockserver.Connection' if not TRACKLESS
    else 'agv05_webserver.systemx.sockserver.Connection',
}

# Licensing
LICENSE_MAX_USERS = 10


# HTTPS request disable warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
urllib3.disable_warnings(urllib3.exceptions.InsecurePlatformWarning)
urllib3.disable_warnings(urllib3.exceptions.SNIMissingWarning)
